%% importModel.m
% 
% Imports the minitaur models generated by the Simscape Multibody link
% plugin. Corrects STEP file references in xml before importing, allong the
% geometry files to reside in a subdirectory. This should be run from the
% project root directory.
% 

%% Set Paths

% Relative path to folder containing generated xml file and STEP models
xmlDirRelPath = 'model_new';
xmlFileName = 'minitaur.xml';
xmlFileBackupName = 'minitaur.xml.old';
path = fullfile(xmlDirRelPath,xmlFileName);

% Back up xml file
copyfile(path,fullfile(xmlDirRelPath,xmlFileBackupName));

%% Set output settings
simName = 'minitaur_temp';
dataName = 'minitaur_model_data_temp';
varName = 'minitaurParamsTemp';

%% Open XML file and modify <GeometryFile> lines.
modelXMLContents = fileread(path);
modelXMLContents = strrep(modelXMLContents,'<GeometryFile name="',['<GeometryFile name="' xmlDirRelPath '/']);

modelXML = fopen(path,'w');
fprintf(modelXML,modelXMLContents);

% Close the xml file
fclose(modelXML);

%% Run smimport(...)
smimport(path,'ModelName',simName,'DataFileName',dataName,'VariableName',varName);